### PR TITLE
Added multiple accounts with settings and environments + their lifecycles

### PR DESCRIPTION
**Pull request by suomiy**
- certificates can be imported from file 
- added rx libs and SqlBrite for rx db queries
- refactor ids and rest
- enhanced syncing, errors and entity updates

- added status bar and Accounts/Clusters menu
- refactored ui activities to MVP with account lifecycles

- optimized triggers ui and floating action button
- events are downloaded for each entity

and other small enhancements and bug fixes

---
This change is [Reviewable](https://reviewable.io/reviews/ovirt/movirt/263)

### CODE REVIEW

**Comment by suomiy** [comment]
- Dasboard, Triggers and Camera still not working

**Comment by suomiy** [comment]
Dashboard done.

**Comment by suomiy** [comment]
Completed. Camera and Triggers fixed.

**Comment by suomiy** [comment]
1.8 alpha 1 is available for testing

**Comment by jelkosz** [comment]
@suomiy For some reason if I use a different domain than internal, I can not log in and movirt complains that 401 unauthorized.

**Comment by suomiy** [comment]
testing apk bumped up to versinon 2.0 alpha 1

**Pull request merged**
