### PR TITLE
[WIP] Multiple engines test sample

### PR DESCRIPTION
**Pull request by suomiy**
@shiramax Could you please check out this branch and tell me what you think about the design of multiple engines' settings? - just the design and navigation. 

btw this is very unstable branch so many features (including simple login) don't work.

---
This change is [Reviewable](https://reviewable.io/reviews/ovirt/movirt/259)

### CODE REVIEW

**Comment by suomiy** [comment]
others are also welcomed to take a look and to give recommendations about the design

P.S. do not merge this branch

**Comment by shiramax** [comment]
@suomiy, i can't add  an engine for some reason, i'm getting this view :
image

but can't press V

**Comment by jelkosz** [comment]
@suomiy ^^^

**Comment by suomiy** [comment]
@shiramax sorry, I couldn't get to it last few days. Should be fixed now

**Comment by shiramax** [comment]
@suomiy , thanks it's working now
1. about adding and account - is it necessary? we can just use the engine fqdn instead 
2. 'SETUP' in the certificated Management - i don't like this button, maybe we should add description "click to setup certificate"

**Comment by suomiy** [comment]
@shiramax 

1. I think it is good to have an option to name it. It is possible there is no fqdn (just an ip) or the fqdn could be too long 
2. I will think about it, that screen is just a draft now

What do you think about the navigation through the settings? Would you change anything?

**Comment by shiramax** [comment]
@suomiy  The navigation through the settings seems OK to me.:)

**Comment by suomiy** [comment]
@shiramax ok, thanks

**Comment by suomiy** [comment]
@shiramax 
2. I will put 'Configure' there. Let me know, if you think something fits better

**Comment by dougti** [comment]
@suomiy, has this been given up on?

**Comment by suomiy** [comment]
1.8 alpha 1 is available for testing in #263

**Pull request closed without merging**
